// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzueztcumkonwglcxakn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dWV6dGN1bWtvbndnbGN4YWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzM0NDEsImV4cCI6MjA2ODAwOTQ0MX0.pT8fK1MKVhsvEJGoeZ3pMCh4PPRjwrwo4gKzXh8rAFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});